### ISSUE TITLE
rewrite it in rust

### ISSUE THREAD

**Issue by ekisu** [salatine/meowrse#1]
i tried to convert the Holy Bible into meowcode to teach my cats how to pray and you wouldnt believe me how __loooooooooooooooooooooooooooong__ it took

rewriting it in rust would make it blazing-fast! :rocket: see below example for reference: https://github.com/mTvare6/hello-world.rs

**Comment by salatine** [comment]
wontfix, send PR if you want ;)

**Comment by ekisu** [comment]
my poor kittens..

**Comment by ekisu** [comment]
i loved the c rewrite! now my kittens can sleep soundly
